version: '3.8'

services:
  node:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "server.js"]
